import { defineConfig } from "oxlint";

export default defineConfig({
  plugins: ["eslint", "typescript", "react", "nextjs", "import", "jsx-a11y", "jest"],
  jsPlugins: [{ name: "turbo", specifier: "eslint-plugin-turbo" }],
  categories: {
    correctness: "off",
  },
  env: {
    builtin: true,
    es2024: true,
    node: true,
  },
  options: {
    typeAware: false,
  },
  settings: {
    next: {
      rootDir: "apps/frontend/",
    },
    react: {
      version: "19.2.8",
    },
  },
  ignorePatterns: [
    "**/dist/**",
    "**/.next/**",
    "**/.turbo/**",
    "**/node_modules/**",
    "apps/frontend/out/**",
    "apps/frontend/build/**",
    "apps/frontend/next-env.d.ts",
    "packages/database/src/generated/**",
    "packages/database/prisma/migrations/**",
  ],
  rules: {
    "constructor-super": "error",
    "for-direction": "error",
    "getter-return": "error",
    "no-async-promise-executor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
      "warn",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "no-array-constructor": "error",
    "no-unused-expressions": "error",
    "turbo/no-undeclared-env-vars": "warn",
    "no-console": ["warn", { allow: ["warn", "error"] }],
    "typescript/ban-ts-comment": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/triple-slash-reference": "error",
  },
  overrides: [
    {
      files: ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
      rules: {
        "constructor-super": "off",
        "getter-return": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unreachable": "off",
        "no-unsafe-negation": "off",
        "no-var": "error",
        "no-with": "off",
        "prefer-const": "error",
        "prefer-rest-params": "error",
        "prefer-spread": "error",
      },
    },
    {
      files: ["apps/backend/**/*.ts"],
      rules: {
        // NestJS decorator metadata and dependency injection require runtime value imports.
        "typescript/consistent-type-imports": "off",
        "typescript/no-explicit-any": "warn",
      },
    },
    {
      files: [
        "apps/backend/**/*.spec.ts",
        "apps/backend/**/*.e2e-spec.ts",
        "apps/backend/test/**/*.ts",
      ],
      env: {
        jest: true,
      },
      rules: {
        "typescript/no-explicit-any": "off",
      },
    },
    {
      files: [
        "apps/frontend/**/*.js",
        "apps/frontend/**/*.jsx",
        "apps/frontend/**/*.mjs",
        "apps/frontend/**/*.ts",
        "apps/frontend/**/*.tsx",
        "apps/frontend/**/*.mts",
        "apps/frontend/**/*.cts",
      ],
      env: {
        browser: true,
      },
      rules: {
        "react/display-name": "error",
        "react/jsx-key": "error",
        "react/jsx-no-comment-textnodes": "error",
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-target-blank": "off",
        "react/jsx-no-undef": "error",
        "react/no-children-prop": "error",
        "react/no-danger-with-children": "error",
        "react/no-direct-mutation-state": "error",
        "react/no-find-dom-node": "error",
        "react/no-is-mounted": "error",
        "react/no-render-return-value": "error",
        "react/no-string-refs": "error",
        "react/no-unescaped-entities": "error",
        "react/no-unknown-property": "off",
        "react/no-unsafe": "off",
        "react/react-in-jsx-scope": "off",
        "react/rules-of-hooks": "error",
        "react/exhaustive-deps": "warn",
        "react/react-compiler": "error",
        "import/no-anonymous-default-export": "warn",
        "jsx-a11y/alt-text": ["warn", { elements: ["img"], img: ["Image"] }],
        "jsx-a11y/aria-props": "warn",
        "jsx-a11y/aria-proptypes": "warn",
        "jsx-a11y/aria-unsupported-elements": "warn",
        "jsx-a11y/role-has-required-aria-props": "warn",
        "jsx-a11y/role-supports-aria-props": "warn",
        "nextjs/google-font-display": "warn",
        "nextjs/google-font-preconnect": "warn",
        "nextjs/next-script-for-ga": "warn",
        "nextjs/no-async-client-component": "warn",
        "nextjs/no-before-interactive-script-outside-document": "warn",
        "nextjs/no-css-tags": "warn",
        "nextjs/no-head-element": "warn",
        "nextjs/no-html-link-for-pages": "warn",
        "nextjs/no-img-element": "warn",
        "nextjs/no-page-custom-font": "warn",
        "nextjs/no-styled-jsx-in-document": "warn",
        "nextjs/no-sync-scripts": "warn",
        "nextjs/no-title-in-document-head": "warn",
        "nextjs/no-typos": "warn",
        "nextjs/no-unwanted-polyfillio": "warn",
        "nextjs/inline-script-id": "error",
        "nextjs/no-assign-module-variable": "error",
        "nextjs/no-document-import-in-page": "error",
        "nextjs/no-duplicate-head": "error",
        "nextjs/no-head-import-in-document": "error",
        "nextjs/no-script-component-in-head": "error",
      },
    },
  ],
});
